# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CoffeeDelivery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoffeeDelivery
  pod 'TakeMePaySDK'
  pod 'TakeMePaySDK-WeChatPaySupport'

  target 'CoffeeDeliveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoffeeDeliveryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
